spring:
  application:
    name: student-assistant
  datasource:
    url: jdbc:postgresql://localhost:5433/student_assistant
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
      embedding:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: false
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

server:
  port: 9090
